---
include:
  - board: nice_nano_v2
    shield: the_keyboard_right
    artifact-name: the_keyboard_black_right
  - board: nice_nano_v2
    shield: the_keyboard_left
    cmake-args: -DZMK_KEYBOARD_NAME=the-keyboard-black
    artifact-name: the_keyboard_black_left
  - board: nice_nano_v2
    shield: the_keyboard_right
    artifact-name: the_keyboard_white_right
  - board: nice_nano_v2
    shield: the_keyboard_left
    cmake-args: -DZMK_KEYBOARD_NAME=the-keyboard-white
    artifact-name: the_keyboard_white_left

 