---
board: [ "nice_nano_v2" ]
shield: [ "the_keyboard_left", "the_keyboard_right" ]
include:
  - board: nice_nano_v2
    shield: the_keyboard_right
  - board: nice_nano_v2
    shield: the_keyboard_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_left_with_studio