---
board: [ "nice_nano_v2" ]
shield: [ "the_keyboard_left", "the_keyboard_right" ]
include:
  - keyboard: black
    board: nice_nano_v2
    shield: the_keyboard_right
  - keyboard: black
    board: nice_nano_v2
    shield: the_keyboard_left
    cmake-args: -DZMK_KEYBOARD_NAME=the-keyboard-black
 