---
board: [ "nice_nano_v2" ]
shield: [ "the_keyboard_left", "the_keyboard_right" ]
include:
  - board: nice_nano_v2
    shield: the_keyboard_right
    artifact-name: the_keyboard_black
  - board: nice_nano_v2
    shield: the_keyboard_left
    cmake-args: -DZMK_KEYBOARD_NAME=the-keyboard-black
    artifact-name: the_keyboard_black